spring:
  datasource:
    password: root123
    url: jdbc:postgresql://localhost:5432/labs
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
          time_zone: America/Bogota

